# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/src/bots"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/src/collectors"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/src/core"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip" 
    directory: "/src/presenters"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip" 
    directory: "/src/publishers"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" 
    directory: "/src/gui"
    schedule:
      interval: "weekly"
