[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "taranis-ng_shared"
version = "25.12.1"
description = "Taranis-NG Shared Classes"
requires-python = ">=3.10"
dependencies = [
    "marshmallow==4.0.0"
]
