[project]
name = "TARANIS-NG-publishers"
version = "v24.11.1"
description = "Taranis-NG Publishers service."
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4==4.13.5",
    "envelope==2.3.0",
    "Flask==3.1.2",
    "Flask-Cors==6.0.1",
    "Flask-RESTful==0.3.10",
    "gevent==25.5.1",
    "gunicorn==23.0.0",
    "marshmallow==4.0.1",
    "Mastodon.py==2.1.3",
    "paramiko==4.0.0",
    "python-dotenv==1.1.1",
    "requests==2.32.5",
    "tweepy==4.16.0",
    "urllib3==2.5.0",
    "pymisp==2.5.17"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
