[project]
name = "TARANIS-NG-core"
version = "v25.12.1"
description = "Taranis-NG Core service."
requires-python = ">=3.10"
dependencies = [
    "alembic==1.17.2",
    "beautifulsoup4==4.14.3",
    "Flask==3.1.2",
    "Flask-Cors==6.0.2",
    "Flask-JWT-Extended==4.7.1",
    "Flask-Migrate==4.1.0",
    "flask-oidc==2.4.0",
    "Flask-RESTful==0.3.10",
    "Flask-SQLAlchemy==3.1.1",
    "gevent==25.9.1",
    "gunicorn==23.0.0",
    "Jinja2==3.1.6",
    "ldap3 @ git+https://github.com/cannatag/ldap3.git@refs/pull/983/head",
    "marshmallow==4.2.0",
    "psycopg[binary]==3.3.2",
    "pycryptodomex==3.23.0",
    "PyJWT==2.10.1",
    "python-dotenv==1.2.1",
    "python-keycloak==7.0.1",
    "requests==2.32.5",
    "schedule==1.2.2",
    "sseclient-py==1.9.0",
    "SQLAlchemy==2.0.45",
    "tqdm==4.67.1",
    "Werkzeug==3.1.4",
    "langchain==1.2.0",
    "langchain-openai==1.1.7"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
